apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-server
  template:
    metadata:
      labels:
        app: authentication-server
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - gke-low-cost-cluster-default-pool-04626fef-gvbc
      containers:
        - name: authentication-server
          image: IMAGE_URL  # This will be replaced by the actual image URL via sed
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              value: jdbc:postgresql://34.71.130.91:5432/postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: AUTH_SERVER
              value: https://34.67.92.189:8080
            - name: AUTH_SERVER_JWKS
              value: https://34.67.92.189:8080/oauth2/jwks
            - name: LOGGING_LEVEL_ROOT  # This variable will set the root log level
              value: "INFO"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC
              value: "INFO"
            - name: LOGGING_LEVEL_COM_EXAMPLE_REPOSITORY
              value: "INFO"
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "50m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-server
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: authentication-server
