apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-server
  template:
    metadata:
      labels:
        app: authentication-server
    spec:
      containers:
        - name: authentication-server
          image: IMAGE_URL  # This will be replaced by the actual image URL via sed
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              value: jdbc:postgresql://34.123.248.164:5432/postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: AUTH_SERVER
              value: http://34.121.119.90:8080
            - name: AUTH_SERVER_JWKS
              value: http://34.121.119.90:8080/oauth2/jwks
            - name: LOGGING_LEVEL_ROOT  # This variable will set the root log level
              value: "DEBUG"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC
              value: "DEBUG"
            - name: LOGGING_LEVEL_COM_EXAMPLE_REPOSITORY
              value: "DEBUG" 
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-server
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: authentication-server
