apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-server
  template:
    metadata:
      labels:
        app: authentication-server
    spec:
      containers:
        - name: authentication-server
          image: borissolomonia/microservices-authentication-server:latest #dockerhub ზე განთავსებული იმიჯია საჭირო
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_SERVER_ADDRESS
              value: "http://reflect-service-registry:8761/eureka"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              value: jdbc:postgresql://10.2.0.8:5432/postgres
            - name: AUTH_SERVER
              value: http://10.2.0.132:8080
            - name: AUTH_SERVER_JWKS
              value: http://10.2.0.132:8080/oauth2/jwks
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-server
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: authentication-server
